/**
 * Create a user
 *
 * `POST /users`
 * Generated by auto-api-hooks — do not edit manually.
 */
import { useMutation } from '@tanstack/react-query'
import type { UseMutationOptions } from '@tanstack/react-query'
import { getClientConfig } from '../client'
import type { CreateUserParams, CreateUserResponse, CreateUserBody } from '../types'
import { createUserResponseSchema } from '../schemas'

export function useCreateUser(options?: UseMutationOptions<CreateUserResponse, Error, { body: CreateUserBody }>) {
  return useMutation<CreateUserResponse, Error, { body: CreateUserBody }>({
    mutationFn: async (vars) => {
      const config = getClientConfig()
      const url = new URL('/users', config.baseUrl)
      const res = await fetch(url.toString(), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...config.headers },
        body: JSON.stringify(vars.body),
      })
      if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)
      const json = await res.json()
      return createUserResponseSchema.parse(json) as CreateUserResponse
    },
    ...options,
  })
}
