/**
 * Delete a user
 *
 * `DELETE /users/{id}`
 * Generated by auto-api-hooks — do not edit manually.
 */
import { useMutation } from '@tanstack/react-query'
import type { UseMutationOptions } from '@tanstack/react-query'
import { getClientConfig } from '../client'
import type { DeleteUserParams, DeleteUserResponse } from '../types'
import { deleteUserResponseSchema } from '../schemas'

export function useDeleteUser(options?: UseMutationOptions<DeleteUserResponse, Error, { params: DeleteUserParams }>) {
  return useMutation<DeleteUserResponse, Error, { params: DeleteUserParams }>({
    mutationFn: async (vars) => {
      const config = getClientConfig()
      const url = new URL(`/users/${vars.params.id}`, config.baseUrl)
      const res = await fetch(url.toString(), {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json', ...config.headers },
      })
      if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)
      const json = await res.json()
      return deleteUserResponseSchema.parse(json) as DeleteUserResponse
    },
    ...options,
  })
}
