/**
 * Get a user by ID
 *
 * `GET /users/{id}`
 * Generated by auto-api-hooks — do not edit manually.
 */
import { useQuery } from '@tanstack/react-query'
import type { UseQueryOptions } from '@tanstack/react-query'
import { getClientConfig } from '../client'
import type { GetUserParams, GetUserResponse } from '../types'
import { getUserResponseSchema } from '../schemas'

export function useGetUser(params: GetUserParams, options?: Partial<UseQueryOptions<GetUserResponse, Error>>) {
  return useQuery<GetUserResponse, Error>({
    queryKey: ['users', 'detail', id] as const,
    queryFn: async () => {
      const config = getClientConfig()
      const url = new URL(`/users/${params.id}`, config.baseUrl)
      const res = await fetch(url.toString(), {
        headers: { 'Content-Type': 'application/json', ...config.headers },
      })
      if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)
      const json = await res.json()
      return getUserResponseSchema.parse(json) as GetUserResponse
    },
    ...options,
  })
}
