/**
 * List all users (infinite)
 *
 * `GET /users`
 * Generated by auto-api-hooks — do not edit manually.
 */
import { useInfiniteQuery } from '@tanstack/react-query'
import type { UseInfiniteQueryOptions } from '@tanstack/react-query'
import { getClientConfig } from '../client'
import type { ListUsersParams, ListUsersResponse } from '../types'
import { listUsersResponseSchema } from '../schemas'

export function useListUsersInfinite(params: Omit<ListUsersParams, 'offset'>, options?: Partial<UseInfiniteQueryOptions<ListUsersResponse, Error>>) {
  return useInfiniteQuery<ListUsersResponse, Error>({
    queryKey: ['users', 'list', params] as const,
    queryFn: async ({ pageParam }) => {
      const config = getClientConfig()
      const url = new URL('/users', config.baseUrl)
      if (params.limit !== undefined) url.searchParams.set('limit', String(params.limit))
      if (pageParam !== undefined) url.searchParams.set('offset', String(pageParam))
      const res = await fetch(url.toString(), {
        headers: { 'Content-Type': 'application/json', ...config.headers },
      })
      if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)
      const json = await res.json()
      return listUsersResponseSchema.parse(json) as ListUsersResponse
    },
    initialPageParam: 0 as number,
    getNextPageParam: (lastPage) => (lastPage as Record<string, unknown>)?.offset as number,
    ...options,
  })
}
