/**
 * MSW browser setup for development.
 * Generated by auto-api-hooks — do not edit manually.
 */
import { setupWorker } from 'msw/browser'
import { handlers } from './handlers'

export const worker = setupWorker(...handlers)
