/**
 * MSW server setup for Node.js (tests, SSR).
 * Generated by auto-api-hooks — do not edit manually.
 */
import { setupServer } from 'msw/node'
import { handlers } from './handlers'

export const server = setupServer(...handlers)
