/**
 * Query key factories for TanStack React Query.
 * Generated by auto-api-hooks — do not edit manually.
 */

export const usersKeys = {
  all: ['users'] as const,
  lists: () => [...usersKeys.all, 'list'] as const,
  list: (params?: Record<string, unknown>) => [...usersKeys.lists(), params] as const,
  details: () => [...usersKeys.all, 'detail'] as const,
  detail: (id: string | number) => [...usersKeys.details(), id] as const,
} as const
