/**
 * Mock data generators.
 * Generated by auto-api-hooks — do not edit manually.
 */

export function generateListUsersMock() {
  return [{
  id: '00000000-0000-0000-0000-000000000001',
  name: 'string-value-0',
  email: 'user@example.com',
  age: 1,
  createdAt: '2024-01-01T00:00:00Z'
}]
}

export function generateCreateUserMock() {
  return {
  id: '00000000-0000-0000-0000-000000000001',
  name: 'string-value-0',
  email: 'user@example.com',
  age: 1,
  createdAt: '2024-01-01T00:00:00Z'
}
}

export function generateGetUserMock() {
  return {
  id: '00000000-0000-0000-0000-000000000001',
  name: 'string-value-0',
  email: 'user@example.com',
  age: 1,
  createdAt: '2024-01-01T00:00:00Z'
}
}

export function generateDeleteUserMock() {
  return 'unknown'
}
