/**
 * MSW request handlers.
 * Generated by auto-api-hooks — do not edit manually.
 */
import { http, HttpResponse } from 'msw'
import * as mocks from './data'

export const handlers = [
  http.get('https://api.example.com/v1/users', () => {
    return HttpResponse.json(mocks.generateListUsersMock(), { status: 200 })
  }),
  http.post('https://api.example.com/v1/users', () => {
    return HttpResponse.json(mocks.generateCreateUserMock(), { status: 201 })
  }),
  http.get('https://api.example.com/v1/users/:id', () => {
    return HttpResponse.json(mocks.generateGetUserMock(), { status: 200 })
  }),
  http.delete('https://api.example.com/v1/users/:id', () => {
    return HttpResponse.json(mocks.generateDeleteUserMock(), { status: 204 })
  }),
]
