import {
  emitMswHandlers,
  emitMswServerSetup,
  emitMswBrowserSetup,
  emitMockIndex,
} from '../../src/mock-gen/index'
import {
  createMockSpec,
  createGetOperation,
  createPostOperation,
  createDetailOperation,
  createDeleteOperation,
} from '../helpers'

describe('emitMswHandlers', () => {
  it('generates valid MSW v2 handler code', () => {
    const spec = createMockSpec()
    const result = emitMswHandlers(spec)
    expect(result).toContain("import { http, HttpResponse } from 'msw'")
    expect(result).toContain("import * as mocks from './data'")
    expect(result).toContain('export const handlers = [')
  })

  it('uses http.get for GET operations', () => {
    const spec = createMockSpec([createGetOperation()])
    const result = emitMswHandlers(spec)
    expect(result).toContain('http.get(')
  })

  it('uses http.post for POST operations', () => {
    const spec = createMockSpec([createPostOperation()])
    const result = emitMswHandlers(spec)
    expect(result).toContain('http.post(')
  })

  it('uses http.delete for DELETE operations', () => {
    const spec = createMockSpec([createDeleteOperation()])
    const result = emitMswHandlers(spec)
    expect(result).toContain('http.delete(')
  })

  it('converts {id} path params to :id format', () => {
    const spec = createMockSpec([createDetailOperation()])
    const result = emitMswHandlers(spec)
    expect(result).toContain(':petId')
    expect(result).not.toContain('{petId}')
  })

  it('prepends baseUrl to paths', () => {
    const spec = createMockSpec([createGetOperation()])
    const result = emitMswHandlers(spec)
    expect(result).toContain('http://localhost:3000/api/pets')
  })

  it('returns HttpResponse.json with correct status code', () => {
    const spec = createMockSpec([createGetOperation()])
    const result = emitMswHandlers(spec)
    expect(result).toContain('HttpResponse.json')
    expect(result).toContain('status: 200')
  })

  it('uses 201 status for POST operations', () => {
    const spec = createMockSpec([createPostOperation()])
    const result = emitMswHandlers(spec)
    expect(result).toContain('status: 201')
  })

  it('uses 204 status for DELETE operations', () => {
    const spec = createMockSpec([createDeleteOperation()])
    const result = emitMswHandlers(spec)
    expect(result).toContain('status: 204')
  })

  it('calls mock data generator functions', () => {
    const spec = createMockSpec([createGetOperation()])
    const result = emitMswHandlers(spec)
    expect(result).toContain('mocks.generateListPetsMock()')
  })

  it('handles multiple operations', () => {
    const spec = createMockSpec([createGetOperation(), createPostOperation(), createDetailOperation()])
    const result = emitMswHandlers(spec)
    expect(result).toContain('http.get(')
    expect(result).toContain('http.post(')
    // Detail operation is also a GET
    const getMatches = result.match(/http\.get\(/g)
    expect(getMatches!.length).toBe(2)
  })
})

describe('emitMswServerSetup', () => {
  it('generates setupServer code for Node.js', () => {
    const result = emitMswServerSetup()
    expect(result).toContain("import { setupServer } from 'msw/node'")
    expect(result).toContain("import { handlers } from './handlers'")
    expect(result).toContain('export const server = setupServer(...handlers)')
  })

  it('contains auto-generation comment', () => {
    const result = emitMswServerSetup()
    expect(result).toContain('Generated by auto-api-hooks')
  })
})

describe('emitMswBrowserSetup', () => {
  it('generates setupWorker code for browser', () => {
    const result = emitMswBrowserSetup()
    expect(result).toContain("import { setupWorker } from 'msw/browser'")
    expect(result).toContain("import { handlers } from './handlers'")
    expect(result).toContain('export const worker = setupWorker(...handlers)')
  })

  it('contains auto-generation comment', () => {
    const result = emitMswBrowserSetup()
    expect(result).toContain('Generated by auto-api-hooks')
  })
})

describe('emitMockIndex', () => {
  it('generates barrel index for mocks', () => {
    const result = emitMockIndex()
    expect(result).toContain("export { handlers } from './handlers'")
    expect(result).toContain("export * from './data'")
  })
})
