/**
 * Create a user
 *
 * `POST /users`
 * Generated by auto-api-hooks — do not edit manually.
 */
import { useState, useCallback } from 'react'
import type { CreateUserParams, CreateUserResponse, CreateUserBody } from '../types'
import { apiClient } from '../client'
import { createUserResponseSchema } from '../schemas'
export interface useCreateUserResult {
  data: CreateUserResponse | null
  error: Error | null
  isLoading: boolean
  mutate: (body: CreateUserBody) => Promise<CreateUserResponse>
  reset: () => void
}

export function useCreateUser(): useCreateUserResult {
  const [data, setData] = useState<CreateUserResponse | null>(null)
  const [error, setError] = useState<Error | null>(null)
  const [isLoading, setIsLoading] = useState(false)

  const mutate = useCallback(async (body: CreateUserBody): Promise<CreateUserResponse> => {
    setIsLoading(true)
    setError(null)

    try {
      const res = await apiClient.post<CreateUserResponse>('/users', body)
      const parsed = createUserResponseSchema.parse(res.data)
      setData(parsed as CreateUserResponse)
      return parsed as CreateUserResponse
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err))
      setError(error)
      throw error
    } finally {
      setIsLoading(false)
    }
  }, [])

  const reset = useCallback(() => {
    setData(null)
    setError(null)
    setIsLoading(false)
  }, [])

  return { data, error, isLoading, mutate, reset }
}
