/**
 * Delete a user
 *
 * `DELETE /users/{id}`
 * Generated by auto-api-hooks — do not edit manually.
 */
import { useState, useCallback } from 'react'
import type { DeleteUserParams, DeleteUserResponse } from '../types'
import { apiClient } from '../client'
import { deleteUserResponseSchema } from '../schemas'
export interface useDeleteUserResult {
  data: DeleteUserResponse | null
  error: Error | null
  isLoading: boolean
  mutate: (params: DeleteUserParams) => Promise<DeleteUserResponse>
  reset: () => void
}

export function useDeleteUser(): useDeleteUserResult {
  const [data, setData] = useState<DeleteUserResponse | null>(null)
  const [error, setError] = useState<Error | null>(null)
  const [isLoading, setIsLoading] = useState(false)

  const mutate = useCallback(async (params: DeleteUserParams): Promise<DeleteUserResponse> => {
    setIsLoading(true)
    setError(null)

    try {
      const res = await apiClient.delete<DeleteUserResponse>(`/users/${params.id}`)
      const parsed = deleteUserResponseSchema.parse(res.data)
      setData(parsed as DeleteUserResponse)
      return parsed as DeleteUserResponse
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err))
      setError(error)
      throw error
    } finally {
      setIsLoading(false)
    }
  }, [])

  const reset = useCallback(() => {
    setData(null)
    setError(null)
    setIsLoading(false)
  }, [])

  return { data, error, isLoading, mutate, reset }
}
