/**
 * Get a user by ID
 *
 * `GET /users/{id}`
 * Generated by auto-api-hooks — do not edit manually.
 */
import { useState, useEffect, useCallback, useRef } from 'react'
import type { GetUserParams, GetUserResponse } from '../types'
import { apiClient } from '../client'
import { getUserResponseSchema } from '../schemas'
export interface useGetUserResult {
  data: GetUserResponse | null
  error: Error | null
  isLoading: boolean
  refetch: () => void
}
export function useGetUser(params: GetUserParams, options?: { enabled?: boolean }): useGetUserResult {
  const [data, setData] = useState<GetUserResponse | null>(null)
  const [error, setError] = useState<Error | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const cancelRef = useRef<(() => void) | null>(null)
  const fetchData = useCallback(async () => {
    if (options?.enabled === false) return
    cancelRef.current?.()
    const source = new AbortController()
    cancelRef.current = () => source.abort()
    setIsLoading(true)
    setError(null)
    try {
      const res = await apiClient.get<GetUserResponse>(`/users/${params.id}`, {
        signal: source.signal,
      })
      const parsed = getUserResponseSchema.parse(res.data)
      setData(parsed as GetUserResponse)
    } catch (err) {
      if (!source.signal.aborted) {
        setError(err instanceof Error ? err : new Error(String(err)))
      }
    } finally {
      setIsLoading(false)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [JSON.stringify(params)])
  useEffect(() => {
    fetchData()
    return () => { cancelRef.current?.() }
  }, [fetchData])
  return { data, error, isLoading, refetch: fetchData }
}
