/**
 * List all users
 *
 * `GET /users`
 * Generated by auto-api-hooks — do not edit manually.
 */
import { useState, useEffect, useCallback, useRef } from 'react'
import type { ListUsersParams, ListUsersResponse } from '../types'
import { apiClient } from '../client'
import { listUsersResponseSchema } from '../schemas'
export interface useListUsersResult {
  data: ListUsersResponse | null
  error: Error | null
  isLoading: boolean
  refetch: () => void
}
export function useListUsers(params: ListUsersParams, options?: { enabled?: boolean }): useListUsersResult {
  const [data, setData] = useState<ListUsersResponse | null>(null)
  const [error, setError] = useState<Error | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const cancelRef = useRef<(() => void) | null>(null)
  const fetchData = useCallback(async () => {
    if (options?.enabled === false) return
    cancelRef.current?.()
    const source = new AbortController()
    cancelRef.current = () => source.abort()
    setIsLoading(true)
    setError(null)
    try {
      const res = await apiClient.get<ListUsersResponse>('/users', {
        params: { limit: params.limit, offset: params.offset },
        signal: source.signal,
      })
      const parsed = listUsersResponseSchema.parse(res.data)
      setData(parsed as ListUsersResponse)
    } catch (err) {
      if (!source.signal.aborted) {
        setError(err instanceof Error ? err : new Error(String(err)))
      }
    } finally {
      setIsLoading(false)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [JSON.stringify(params)])
  useEffect(() => {
    fetchData()
    return () => { cancelRef.current?.() }
  }, [fetchData])
  return { data, error, isLoading, refetch: fetchData }
}
