/**
 * Deterministic mock data generation from IR types.
 *
 * No faker.js dependency — generates simple, predictable values
 * so the generated mock code has zero runtime dependencies.
 */
import type { ApiType, ApiSpec, ApiOperation } from '../ir/types'

let counter = 0

function resetCounter(): void {
  counter = 0
}

/**
 * Generate a mock value expression (as a code string) for a given type.
 */
export function emitMockValue(type: ApiType, spec: ApiSpec, depth = 0): string {
  if (depth > 5) return `null`

  switch (type.kind) {
    case 'primitive':
      return emitPrimitiveMock(type.type, type.format)
    case 'object':
      return emitObjectMock(type, spec, depth)
    case 'array':
      return `[${emitMockValue(type.items, spec, depth + 1)}]`
    case 'enum':
      if (type.values.length === 0) return `null`
      const val = type.values[0]
      return typeof val === 'string' ? `'${val}'` : String(val)
    case 'union':
      if (type.variants.length === 0) return `null`
      return emitMockValue(type.variants[0], spec, depth + 1)
    case 'ref': {
      const resolved = spec.types.get(type.name)
      if (resolved) return emitMockValue(resolved, spec, depth + 1)
      return `{}`
    }
    default:
      return `null`
  }
}

function emitPrimitiveMock(type: string, format?: string): string {
  switch (type) {
    case 'string':
      return emitStringMock(format)
    case 'number':
    case 'integer':
      return String(counter++)
    case 'boolean':
      return 'true'
    case 'null':
      return 'null'
    default:
      return `'unknown'`
  }
}

function emitStringMock(format?: string): string {
  switch (format) {
    case 'date-time':
      return `'2024-01-01T00:00:00Z'`
    case 'date':
      return `'2024-01-01'`
    case 'email':
      return `'user@example.com'`
    case 'uuid':
      return `'00000000-0000-0000-0000-000000000001'`
    case 'uri':
    case 'url':
      return `'https://example.com'`
    case 'hostname':
      return `'example.com'`
    case 'ipv4':
      return `'127.0.0.1'`
    case 'ipv6':
      return `'::1'`
    default:
      return `'string-value-${counter++}'`
  }
}

function emitObjectMock(type: ApiType & { kind: 'object' }, spec: ApiSpec, depth: number): string {
  if (type.properties.length === 0) {
    return `{}`
  }

  const props = type.properties
    .map((p) => `  ${safeKey(p.name)}: ${emitMockValue(p.type, spec, depth + 1)}`)
    .join(',\n')

  return `{\n${props}\n}`
}

function safeKey(name: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : `'${name}'`
}

/**
 * Generate a mock data function for an operation's response type.
 */
export function emitMockDataFunction(
  op: ApiOperation,
  spec: ApiSpec,
): string {
  resetCounter()
  const fnName = `generate${op.operationId.charAt(0).toUpperCase() + op.operationId.slice(1)}Mock`
  const mockValue = emitMockValue(op.response.type, spec)

  return [
    `export function ${fnName}() {`,
    `  return ${mockValue}`,
    `}`,
  ].join('\n')
}

/**
 * Generate the full mock data file.
 */
export function emitMockDataFile(spec: ApiSpec): string {
  const lines: string[] = [
    `/**`,
    ` * Mock data generators.`,
    ` * Generated by auto-api-hooks — do not edit manually.`,
    ` */`,
    ``,
  ]

  for (const op of spec.operations) {
    resetCounter()
    lines.push(emitMockDataFunction(op, spec))
    lines.push(``)
  }

  return lines.join('\n')
}
