/**
 * MSW v2 request handler generator.
 */
import type { ApiSpec, ApiOperation, HttpMethod } from '../ir/types'

/**
 * Generate MSW handler file content.
 */
export function emitMswHandlers(spec: ApiSpec): string {
  const lines: string[] = [
    `/**`,
    ` * MSW request handlers.`,
    ` * Generated by auto-api-hooks — do not edit manually.`,
    ` */`,
    `import { http, HttpResponse } from 'msw'`,
    `import * as mocks from './data'`,
    ``,
    `export const handlers = [`,
  ]

  for (const op of spec.operations) {
    // Skip non-HTTP operations (GraphQL queries/mutations/subscriptions)
    if (!isHttpMethod(op.method)) continue

    const mswMethod = op.method.toLowerCase()
    const mswPath = convertPathToMsw(op.path, spec.baseUrl)
    const mockFnName = `generate${op.operationId.charAt(0).toUpperCase() + op.operationId.slice(1)}Mock`
    const statusCode = getStatusCode(op)

    lines.push(
      `  http.${mswMethod}('${mswPath}', () => {`,
      `    return HttpResponse.json(mocks.${mockFnName}(), { status: ${statusCode} })`,
      `  }),`,
    )
  }

  lines.push(
    `]`,
    ``,
  )

  return lines.join('\n')
}

/**
 * Generate the MSW server setup file (Node.js).
 */
export function emitMswServerSetup(): string {
  return [
    `/**`,
    ` * MSW server setup for Node.js (tests, SSR).`,
    ` * Generated by auto-api-hooks — do not edit manually.`,
    ` */`,
    `import { setupServer } from 'msw/node'`,
    `import { handlers } from './handlers'`,
    ``,
    `export const server = setupServer(...handlers)`,
    ``,
  ].join('\n')
}

/**
 * Generate the MSW browser setup file.
 */
export function emitMswBrowserSetup(): string {
  return [
    `/**`,
    ` * MSW browser setup for development.`,
    ` * Generated by auto-api-hooks — do not edit manually.`,
    ` */`,
    `import { setupWorker } from 'msw/browser'`,
    `import { handlers } from './handlers'`,
    ``,
    `export const worker = setupWorker(...handlers)`,
    ``,
  ].join('\n')
}

/**
 * Generate the barrel index for mocks.
 */
export function emitMockIndex(): string {
  return [
    `export { handlers } from './handlers'`,
    `export * from './data'`,
    ``,
  ].join('\n')
}

/**
 * Convert an OpenAPI path to MSW path format.
 * `/users/{id}` → `/users/:id`
 */
function convertPathToMsw(path: string, baseUrl: string): string {
  const mswPath = path.replace(/\{(\w+)\}/g, ':$1')
  if (baseUrl) {
    return `${baseUrl}${mswPath}`
  }
  return mswPath
}

function isHttpMethod(method: string): method is HttpMethod {
  return ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS'].includes(method)
}

function getStatusCode(op: ApiOperation): number {
  if (op.response.statusCode !== 'default' && typeof op.response.statusCode === 'number') {
    return op.response.statusCode
  }
  // Default status codes by method
  switch (op.method) {
    case 'POST':
      return 201
    case 'DELETE':
      return 204
    default:
      return 200
  }
}
