/**
 * Axios API client configuration.
 * Generated by auto-api-hooks — do not edit manually.
 */
import axios from 'axios'

export const API_BASE_URL = 'https://api.example.com/v1'

export const apiClient = axios.create({
  baseURL: API_BASE_URL,
  headers: { 'Content-Type': 'application/json' },
})

/**
 * Configure the API client.
 */
export function configureClient(config: { baseUrl?: string; headers?: Record<string, string> }): void {
  if (config.baseUrl) apiClient.defaults.baseURL = config.baseUrl
  if (config.headers) Object.assign(apiClient.defaults.headers.common, config.headers)
}
