/**
 * API client configuration.
 * Generated by auto-api-hooks — do not edit manually.
 */

export const API_BASE_URL = 'https://api.example.com/v1'

export interface ClientConfig {
  baseUrl: string
  headers?: Record<string, string>
}

let _config: ClientConfig = {
  baseUrl: API_BASE_URL,
}

/**
 * Configure the API client.
 */
export function configureClient(config: Partial<ClientConfig>): void {
  _config = { ..._config, ...config }
}

/**
 * Get the current client configuration.
 */
export function getClientConfig(): ClientConfig {
  return _config
}
