/**
 * Create a user
 *
 * `POST /users`
 * Generated by auto-api-hooks — do not edit manually.
 */
import useSWRMutation from 'swr/mutation'
import { getClientConfig } from '../client'
import type { CreateUserParams, CreateUserResponse, CreateUserBody } from '../types'
import { createUserResponseSchema } from '../schemas'

export function useCreateUser() {
  return useSWRMutation<CreateUserResponse, Error, string, { body: CreateUserBody }>(
    'POST /users',
    async (_key: string, { arg }: { arg: { body: CreateUserBody } }) => {
      const config = getClientConfig()
      const url = new URL('/users', config.baseUrl)
      const res = await fetch(url.toString(), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...config.headers },
        body: JSON.stringify(arg.body),
      })
      if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)
      const json = await res.json()
      return createUserResponseSchema.parse(json) as CreateUserResponse
    },
  )
}
