/**
 * Delete a user
 *
 * `DELETE /users/{id}`
 * Generated by auto-api-hooks — do not edit manually.
 */
import useSWRMutation from 'swr/mutation'
import { getClientConfig } from '../client'
import type { DeleteUserParams, DeleteUserResponse } from '../types'
import { deleteUserResponseSchema } from '../schemas'

export function useDeleteUser() {
  return useSWRMutation<DeleteUserResponse, Error, string, { params: DeleteUserParams }>(
    'DELETE /users/{id}',
    async (_key: string, { arg }: { arg: { params: DeleteUserParams } }) => {
      const config = getClientConfig()
      const url = new URL(`/users/${arg.params.id}`, config.baseUrl)
      const res = await fetch(url.toString(), {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json', ...config.headers },
      })
      if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)
      const json = await res.json()
      return deleteUserResponseSchema.parse(json) as DeleteUserResponse
    },
  )
}
