/**
 * Get a user by ID
 *
 * `GET /users/{id}`
 * Generated by auto-api-hooks — do not edit manually.
 */
import useSWR from 'swr'
import type { SWRConfiguration } from 'swr'
import { getClientConfig } from '../client'
import type { GetUserParams, GetUserResponse } from '../types'
import { getUserResponseSchema } from '../schemas'

export function useGetUser(params: GetUserParams, options?: { enabled?: boolean }) {
  const key = options?.enabled === false ? null : `/users/${id}`

  return useSWR<GetUserResponse, Error>(key, async () => {
    const config = getClientConfig()
    const url = new URL(`/users/${params.id}`, config.baseUrl)
    const res = await fetch(url.toString(), {
      headers: { 'Content-Type': 'application/json', ...config.headers },
    })
    if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)
    const json = await res.json()
    return getUserResponseSchema.parse(json) as GetUserResponse
  })
}
