/**
 * List all users (infinite)
 *
 * `GET /users`
 * Generated by auto-api-hooks — do not edit manually.
 */
import useSWRInfinite from 'swr/infinite'
import { getClientConfig } from '../client'
import type { ListUsersParams, ListUsersResponse } from '../types'
import { listUsersResponseSchema } from '../schemas'

export function useListUsersInfinite(params: Omit<ListUsersParams, 'offset'>) {
  const getKey = (pageIndex: number, previousPageData: ListUsersResponse | null) => {
    if (previousPageData && !(previousPageData as Record<string, unknown>)?.offset) return null
    const pageParam = pageIndex === 0
      ? undefined
      : (previousPageData as Record<string, unknown>)?.offset
    return ['/users', pageParam, params] as const
  }

  return useSWRInfinite<ListUsersResponse, Error>(getKey, async ([_path, pageParam]) => {
    const config = getClientConfig()
    const url = new URL('/users', config.baseUrl)
    if (params.limit !== undefined) url.searchParams.set('limit', String(params.limit))
    if (pageParam !== undefined) url.searchParams.set('offset', String(pageParam))
    const res = await fetch(url.toString(), {
      headers: { 'Content-Type': 'application/json', ...config.headers },
    })
    if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)
    const json = await res.json()
    return listUsersResponseSchema.parse(json) as ListUsersResponse
  })
}
