/**
 * List all users
 *
 * `GET /users`
 * Generated by auto-api-hooks — do not edit manually.
 */
import useSWR from 'swr'
import type { SWRConfiguration } from 'swr'
import { getClientConfig } from '../client'
import type { ListUsersParams, ListUsersResponse } from '../types'
import { listUsersResponseSchema } from '../schemas'

export function useListUsers(params: ListUsersParams, options?: { enabled?: boolean }) {
  const key = options?.enabled === false ? null : `/users?${new URLSearchParams(params as Record<string, string>).toString()}`

  return useSWR<ListUsersResponse, Error>(key, async () => {
    const config = getClientConfig()
    const url = new URL('/users', config.baseUrl)
    if (params.limit !== undefined) url.searchParams.set('limit', String(params.limit))
    if (params.offset !== undefined) url.searchParams.set('offset', String(params.offset))
    const res = await fetch(url.toString(), {
      headers: { 'Content-Type': 'application/json', ...config.headers },
    })
    if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)
    const json = await res.json()
    return listUsersResponseSchema.parse(json) as ListUsersResponse
  })
}
