/**
 * Create a user
 *
 * `POST /users`
 * Generated by auto-api-hooks — do not edit manually.
 */
import { useState, useEffect, useCallback, useRef } from 'react'
import { getClientConfig } from '../client'
import type { CreateUserParams, CreateUserResponse, CreateUserBody } from '../types'
import { createUserResponseSchema } from '../schemas'

export interface useCreateUserResult {
  data: CreateUserResponse | null
  error: Error | null
  isLoading: boolean
  mutate: (body: CreateUserBody) => Promise<CreateUserResponse>
  reset: () => void
}
export function useCreateUser(): useCreateUserResult {
  const [data, setData] = useState<CreateUserResponse | null>(null)
  const [error, setError] = useState<Error | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const mutate = useCallback(async (body: CreateUserBody): Promise<CreateUserResponse> => {
    setIsLoading(true)
    setError(null)
    try {
      const config = getClientConfig()
      const url = buildUrl(config.baseUrl, undefined)
      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...config.headers },
        body: JSON.stringify(body),
      })
      if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)
      const json = await res.json()
      const parsed = createUserResponseSchema.parse(json)
      setData(parsed as CreateUserResponse)
      return parsed as CreateUserResponse
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err))
      setError(error)
      throw error
    } finally {
      setIsLoading(false)
    }
  }, [])
  const reset = useCallback(() => {
    setData(null)
    setError(null)
    setIsLoading(false)
  }, [])
  return { data, error, isLoading, mutate, reset }
}
function buildUrl(baseUrl: string, _params: undefined): string {
  return `${baseUrl}/users`
}
