/**
 * Delete a user
 *
 * `DELETE /users/{id}`
 * Generated by auto-api-hooks — do not edit manually.
 */
import { useState, useEffect, useCallback, useRef } from 'react'
import { getClientConfig } from '../client'
import type { DeleteUserParams, DeleteUserResponse } from '../types'
import { deleteUserResponseSchema } from '../schemas'

export interface useDeleteUserResult {
  data: DeleteUserResponse | null
  error: Error | null
  isLoading: boolean
  mutate: (params: DeleteUserParams) => Promise<DeleteUserResponse>
  reset: () => void
}
export function useDeleteUser(): useDeleteUserResult {
  const [data, setData] = useState<DeleteUserResponse | null>(null)
  const [error, setError] = useState<Error | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const mutate = useCallback(async (params: DeleteUserParams): Promise<DeleteUserResponse> => {
    setIsLoading(true)
    setError(null)
    try {
      const config = getClientConfig()
      const url = buildUrl(config.baseUrl, params)
      const res = await fetch(url, {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json', ...config.headers },
      })
      if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)
      const json = await res.json()
      const parsed = deleteUserResponseSchema.parse(json)
      setData(parsed as DeleteUserResponse)
      return parsed as DeleteUserResponse
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err))
      setError(error)
      throw error
    } finally {
      setIsLoading(false)
    }
  }, [])
  const reset = useCallback(() => {
    setData(null)
    setError(null)
    setIsLoading(false)
  }, [])
  return { data, error, isLoading, mutate, reset }
}
function buildUrl(baseUrl: string, params: DeleteUserParams): string {
  let url = `${baseUrl}/users/${params.id}`
  return url
}
