/**
 * Get a user by ID
 *
 * `GET /users/{id}`
 * Generated by auto-api-hooks — do not edit manually.
 */
import { useState, useEffect, useCallback, useRef } from 'react'
import { getClientConfig } from '../client'
import type { GetUserParams, GetUserResponse } from '../types'
import { getUserResponseSchema } from '../schemas'

export interface useGetUserResult {
  data: GetUserResponse | null
  error: Error | null
  isLoading: boolean
  refetch: () => void
}

export function useGetUser(params: GetUserParams, options?: { enabled?: boolean }): useGetUserResult {
  const [data, setData] = useState<GetUserResponse | null>(null)
  const [error, setError] = useState<Error | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const abortRef = useRef<AbortController | null>(null)

  const fetchData = useCallback(async () => {
    if (options?.enabled === false) return
    abortRef.current?.abort()
    const controller = new AbortController()
    abortRef.current = controller

    setIsLoading(true)
    setError(null)

    try {
      const config = getClientConfig()
      const url = buildUrl(config.baseUrl, params)
      const res = await fetch(url, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json', ...config.headers },
        signal: controller.signal,
      })

      if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)

      const json = await res.json()
      const parsed = getUserResponseSchema.parse(json)
      setData(parsed as GetUserResponse)
    } catch (err) {
      if (err instanceof Error && err.name !== 'AbortError') {
        setError(err)
      }
    } finally {
      setIsLoading(false)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [JSON.stringify(params)])

  useEffect(() => {
    fetchData()
    return () => { abortRef.current?.abort() }
  }, [fetchData])

  return { data, error, isLoading, refetch: fetchData }
}

function buildUrl(baseUrl: string, params: GetUserParams): string {
  let url = `${baseUrl}/users/${params.id}`
  return url
}
