/**
 * List all users
 *
 * `GET /users`
 * Generated by auto-api-hooks — do not edit manually.
 */
import { useState, useEffect, useCallback, useRef } from 'react'
import { getClientConfig } from '../client'
import type { ListUsersParams, ListUsersResponse } from '../types'
import { listUsersResponseSchema } from '../schemas'

export interface useListUsersResult {
  data: ListUsersResponse | null
  error: Error | null
  isLoading: boolean
  refetch: () => void
}

export function useListUsers(params: ListUsersParams, options?: { enabled?: boolean }): useListUsersResult {
  const [data, setData] = useState<ListUsersResponse | null>(null)
  const [error, setError] = useState<Error | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const abortRef = useRef<AbortController | null>(null)

  const fetchData = useCallback(async () => {
    if (options?.enabled === false) return
    abortRef.current?.abort()
    const controller = new AbortController()
    abortRef.current = controller

    setIsLoading(true)
    setError(null)

    try {
      const config = getClientConfig()
      const url = buildUrl(config.baseUrl, params)
      const res = await fetch(url, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json', ...config.headers },
        signal: controller.signal,
      })

      if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)

      const json = await res.json()
      const parsed = listUsersResponseSchema.parse(json)
      setData(parsed as ListUsersResponse)
    } catch (err) {
      if (err instanceof Error && err.name !== 'AbortError') {
        setError(err)
      }
    } finally {
      setIsLoading(false)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [JSON.stringify(params)])

  useEffect(() => {
    fetchData()
    return () => { abortRef.current?.abort() }
  }, [fetchData])

  return { data, error, isLoading, refetch: fetchData }
}

function buildUrl(baseUrl: string, params: ListUsersParams): string {
  let url = `${baseUrl}/users`
  const query = new URLSearchParams()
  if (params.limit !== undefined) query.set('limit', String(params.limit))
  if (params.offset !== undefined) query.set('offset', String(params.offset))
  const qs = query.toString()
  if (qs) url += `?${qs}`
  return url
}
